#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars
env

export TP_KFK_HOST="${TP_KFK_HOST:=kafka}"
export TP_KFK_PORT="${TP_KFK_PORT:=2181}"
export TP_KFK_CLIENT="${TP_KFK_CLIENT:=telepat-producer}"

export TP_REDIS_HOST="${TP_REDIS_HOST:=redis}"
export TP_REDIS_PORT="${TP_REDIS_PORT:=6379}"

export TP_ES_HOST="${TP_ES_HOST:=elasticsearch}"
export TP_ES_PORT="${TP_ES_PORT:=9200}"
export TP_ES_INDEX="${TP_ES_INDEX:=default}"
export TP_MAIN_DB="${TP_MAIN_DB:=ElasticSearch}"

export TP_PW_SALT="${TP_PW_SALT:='$2a$10$N9qo8uLOickgx2ZMRZoMye'}"

curl -XPUT ${TP_ES_HOST}:${TP_ES_PORT}/${TP_ES_INDEX} -d '{"mappings": { "_default_": { "dynamic_templates": [
                                                                             {
                                                                                 "string_template": {
                                                                                     "mapping": {
                                                                                         "index": "not_analyzed",
                                                                                         "type": "string"
                                                                                     },
                                                                                     "match_mapping_type": "string",
                                                                                     "match": "*"
                                                                                 }
                                                                             }
                                                                         ]
                                                                     }
                                                                 },
                                                                 "settings": {
                                                                     "index": {
                                                                         "number_of_replicas": "1",
                                                                         "number_of_shards": "1"
                                                                     }
                                                                 }
                                                             }'
cd /telepat-api
exec 2>&1
exec ./bin/www
